when:
  - event: tag

steps:
  - name: build-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ghcr.io/kalvadtech/woodpecker-opengrep
      tags: latest
      tags_auto: true
      platforms: linux/amd64,linux/arm64
      dockerfile: Dockerfile
      registry: ghcr.io
      username: kalvadtech
      password:
        from_secret: ghcr_token
    when:
      - event: tag

depends_on:
  - clone
